# Generated by Django 2.2.2 on 2019-09-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Grouping',
            fields=[
                ('serviceNumber', models.CharField(max_length=12, unique=True)),
                ('servicePassword', models.CharField(max_length=20)),
                ('serviceGroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Service')),
                ('serviceZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.EDC')),
            ],
        ),
    ]
