# Generated by Django 2.2.2 on 2019-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_edc_service_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edc',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
