# Generated by Django 2.2.2 on 2019-09-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190922_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_grouping',
            name='id',
            field=models.AutoField(auto_created=True, default=90, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_grouping',
            name='serviceGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Service'),
        ),
    ]
