# Generated by Django 2.2.2 on 2019-09-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190926_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorreadings',
            name='chargesC008',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
