# Generated by Django 2.2.2 on 2019-10-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_generatorreadings_chargesc008'),
    ]

    operations = [
        migrations.CreateModel(
            name='meterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readingID', models.CharField(max_length=10, unique=True)),
                ('serviceNumber', models.CharField(blank=True, max_length=12)),
                ('month', models.CharField(blank=True, max_length=2)),
                ('year', models.CharField(blank=True, max_length=150)),
                ('netUnitsC1', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('netUnitsC2', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('netUnitsC3', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('netUnitsC4', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('netUnitsC5', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
            ],
        ),
    ]
