# Generated by Django 2.2.5 on 2019-09-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('place', models.CharField(max_length=25)),
            ],
        ),
    ]
