# Generated by Django 2.2.5 on 2019-09-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_edcmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceNumber', models.CharField(max_length=12, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
                ('edc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.EDCModel')),
            ],
        ),
    ]
